OnlineTedrisGit/Models/DbModels/AdminUser.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineTedris.Models.DbModels
{
    public class AdminUser
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Username { get; set; }
        public string Passvords { get; set; }
    }
}

OnlineTedrisGit/Models/DbModels/TehsilKateqoriya.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineTedris.Models.DbModels
{
    public class TehsilKateqoriya
    {
        public int ID { get; set; }
        public string KateqoriyaAdi { get; set; }
        public List<TedrisSaheleri> TedrisSaheleris { get; set; }
    }
}

OnlineTedrisGit/Controllers/AdminUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineTedris.Models.DbModels;
using OnlineTedris.Context;

namespace OnlineTedris.Controllers
{
    public class AdminUserController : Controller
    {
        // GET: AdminUser
        DbTraining db = new DbTraining();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult LoginAdmin(AdminUser adminUser)
        {
            if (!ModelState.IsValid)
            {
                return View("Index");
            }
            var istifadeci = db.AdminUsers.FirstOrDefault(x => x.Username == adminUser.Username && x.Passvords == adminUser.Passvords);
            if (istifadeci!=null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.message = "Istifadəçi adı və ya şifrə yalnışdır!";
                return View();
            }            
        }
        public ActionResult TehsilKateqoriya()
        {
            var TBKateqoriya = db.TehsilKateqoriyas.ToList();
            return View(TBKateqoriya);
        }
    }
}

OnlineTedrisGit/Views/AdminUser/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/AdminUser/Shared/_Layout.cshtml";
}

<h2 class="text-body" style="text-align:center;padding-top:200px;">Onlayn təhsil idarə etmə sistemi</h2>

OnlineTedrisGit/Views/AdminUser/LoginAdmin.cshtml
@model OnlineTedris.Models.DbModels.AdminUser
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Login</title>
    <!-- Custom fonts for this template-->
    <link href="~/Content/AdminStyle/Adminn/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template-->
    <link href="~/Content/AdminStyle/Adminn/css/sb-admin.css" rel="stylesheet">
</head>
<body class="bg-dark">
    <div class="container">
        <div class="card card-login mx-auto mt-5">
            <div class="card-header">Giriş səhifəsi</div>
            <div class="card-body">
                @using (Html.BeginForm("LoginAdmin", "AdminUser", FormMethod.Post))
                {
                    @Html.AntiForgeryToken() //Link ile gelende emeliyyet yerine yetirmir
                    <div class="form-group">
                        <div class="form-label-group">
                            @Html.LabelFor(m => m.Username)
                            @Html.TextBoxFor(m => m.Username, new { @class = "form-control", placeholder = "İstifadəçi adı", required = "required", autofocus = "autofocus" })
                            @Html.ValidationMessageFor(m => m.Username)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-label-group">
                            @Html.LabelFor(m => m.Passvords)
                            @Html.PasswordFor(m => m.Passvords, new { @class = "form-control", placeholder = "Şifrə", required = "required" })
                            @Html.ValidationMessageFor(m => m.Passvords)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" value="remember-me">
                                Şifrəni xatırlat
                            </label>
                        </div>
                    </div>

                    <button class="btn btn-primary btn-block">Daxil ol</button>
                    @*<div class="text-center">
                            <a class="d-block small mt-3" href="register.html">Register an Account</a>
                            <a class="d-block small" href="forgot-password.html">Forgot Password?</a>
                        </div>*@
                }
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="~/Content/AdminStyle/Adminn/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/AdminStyle/Adminn/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/Content/AdminStyle/Adminn/vendor/jquery-easing/jquery.easing.min.js"></script>
</body>
</html>

OnlineTedrisGit/Views/AdminUser/TehsilKateqoriya.cshtml
@using OnlineTedris.Models.DbModels
@model List<TehsilKateqoriya>

@{
    ViewBag.Title = "TehsilKateqoriya";
    Layout = "~/Views/AdminUser/Shared/_Layout.cshtml";
}
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Kateqoriya adı</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var tk in Model)
                    {
                        <tr><td>@tk.ID</td><td>@tk.KateqoriyaAdi</td></tr>
                    }
                </tbody>
            </table>
        </div>
    </div>